package com.rpgenerator.core.api

import kotlinx.coroutines.flow.Flow

/**
 * Active game instance.
 * Processes player input and emits game events.
 */
abstract class Game internal constructor(
    val id: String,
    private val llm: LLMInterface
) {
    /**
     * Process player input and emit resulting game events as a stream.
     * Events are emitted as they are generated by AI agents.
     *
     * @param input Player text input (from voice or keyboard)
     * @return Flow of game events (narration, NPC dialogue, system notifications, etc.)
     */
    abstract suspend fun processInput(input: String): Flow<GameEvent>

    /**
     * Get current game state snapshot for UI display.
     * Non-suspending - returns cached state.
     */
    abstract fun getState(): GameStateSnapshot

    /**
     * Save current game state to persistent storage.
     */
    abstract suspend fun save()
}
